/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp1 {
  MyFlutterApp1._();

  static const _kFontFam = 'MyFlutterApp1';
  static const String? _kFontPkg = null;

  static const IconData call = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_alt = IconData(0xf5d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
