/// Flutter icons MyIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_right_4 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_5 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_6 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_7 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_8 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_9 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_10 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_11 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_12 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_13 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_14 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_15 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_1 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_normal = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct_up = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash_1 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash_2 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_28 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_1 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_2 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_4 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_3 = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_5 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_6 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_7 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_8 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_9 = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_10 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_11 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_12 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_1 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_2 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_3 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_4 = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circle = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_1 = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_1 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_2 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_3 = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_circle = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_circle_1 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_circle_2 = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_circle_3 = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_normal = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_normal_1 = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_2 = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_normal_2 = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_2 = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_1 = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_3 = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_1 = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_1 = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_2 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_3 = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_1 = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_2 = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_3 = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope_square = IconData(0xf199, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vuesax_linear_camera = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aq1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cameras = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calls = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
